# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SignUp and Login' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SignUp and Login
  pod 'Alamofire', '~> 4.0.0'
  pod 'ObjectMapper', '~> 3.2.0'
  pod 'AwesomeCache', '~> 5.0.0'
  pod 'SVProgressHUD'
  

end
