//
// PropertyAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire

// swiftlint:disable function_parameter_count
protocol PropertyAPI {

}
extension PropertyAPI {
    /**
    Property List
    - parameter pageNo: (query) page Number 
    - parameter body: (body) Longitude,Latitude,Startdate,EndDate..All are optional. (optional)
    - parameter handler: completion handler to receive the data
    */
    func propertyList(_ pageNo: Int, body: Property? = nil, withHandler handler: @escaping (_ responseData: NSIResponse<PropertyList>?) -> Void) {
        let path = "/property/properties/"
        let URLString = Configuration.BaseURL() + path
        let headers = Configuration.customHeaders
        let parameters = body?.encodeToJSON() 
        let convertedParameters = APIHelper.convertBoolToString(source: parameters)
        let requestBuilder = RequestBuilder(urlString: URLString, requestMethod: "POST", requestParameters: convertedParameters, requestHeaders: headers, showLoader: true)
        JSONRequest(requestBuilder: requestBuilder) { (response, isLoadedFromCache) in
            if response.result.isSuccess {
                guard let jsonResponse = response.result.value as? [String: AnyObject] else {
                handler(NSIResponse<PropertyList>(.nilResponse))
                return
            }
            var nsiResponse = NSIResponse<PropertyList>(JSON: jsonResponse)
            nsiResponse?.hasCache = isLoadedFromCache
            handler(nsiResponse)
            } else {
                handler(NSIResponse<PropertyList>(.invalidStatus))
            }
        }
    }
}
