# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Reach' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Reach
  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'SVProgressHUD'
  pod 'AwesomeCache'
  pod 'BartyCrouch'
  pod 'JRMFloatingAnimation'
  pod 'AWSS3'
  pod 'ALCameraViewController'
  pod 'SVProgressHUD'
  pod 'SnapSDK', :subspecs => ['SCSDKLoginKit', 'SCSDKCreativeKit', 'SCSDKBitmojiKit']
  pod 'Kingfisher'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Fabric'
  pod 'Crashlytics'
  
  target 'ReachTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
